# .github/workflows/build.yml
name: Build App

on:
  push:
    branches:
      - workflows  # измени на нужную ветку
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонировать репозиторий
        uses: actions/checkout@v3

      - name: ☕ Установить Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # или 21, если используешь Java 21

      - name: 🔧 Дать права на выполнение Gradle
        run: chmod +x gradlew

      - name: 🧱 Собрать проект
        run: ./gradlew build

      - name: 📦 Сохранить jar файл как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
